FROM node:26

WORKDIR /app

# Keep dependency installation in a cacheable layer.
COPY app/package.json package.json
COPY app/package-lock.json package-lock.json

RUN npm ci

COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production
RUN make build

CMD make start
